/* 
AUTOCOMMIT - BY DEFAULT EVERY SQL SAVES AUTOMATICALLY WE COULDN'T GO BACK TO PREVIOUS VERSION OR PREVIOUS CODE IF AUTOCOMMIT IS TURNED OFF WE CAN RESTORE
COMMIT - IF AUTOCOMMIT IS OFF, AFTER WRITING THE CODE WE NEED TO MANUALLY SAVES THE CODE USING COMMIT 
ROLLBACK - TO RESTORE PREVIOUS VERSION WE USE ROLLBACK
*/

SET AUTOCOMMIT = OFF;

-- if I forgottenly delete all rows in table, use ROLLBACK to restore previous version

DELETE FROM employees;
SELECT * FROM employees;

-- use ROLLBACK to restore previous version 
ROLLBACK;
SELECT * FROM employees;

-- use COMMIT to save sql
DELETE FROM employees where first_name = "nithilan";
COMMIT;
SELECT * FROM employees;